name: Java Presubmit

on: [push]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          skipCommit: true
      - uses: EndBug/add-and-commit@v4
        with:
          author_email: acnwigwe@google.com
          message: "Autoformat java files"
          add: "*.java"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
