name: Feature Branch Front End Tests

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run Jest tests
      run: |
        cd project/src/test/webapp
        npm test